spring:
  cloud:
    stream:
      binders:
        rabbitCluster:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: ${spring.rabbitmq.addresses}
                cache:
                  channel:
                    checkout-timeout: 1s
                    size: 100
                  connection:
                    mode: channel
                connection-timeout: 3s
                password: ${spring.rabbitmq.password}
                username: ${spring.rabbitmq.username}
                virtual-host: ${spring.rabbitmq.virtual-host}
      bindings:
        springCloudBusInput:
          binder: rabbitCluster
          destination: sacl.destination1
          group: saclGroup
          contentType: application/json
        springCloudBusOutput:
          binder: rabbitCluster
          destination: sacl.destination2
          group: saclGroup
          contentType: application/json
          producer:
            errorChannelEnabled:


